[package]
name = "pucklamotzer09"
version = "0.1.0"
authors = ["PucklaMotzer09, https://github.com/PucklaMotzer09"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
