[package]
name = "pucklamotzer09"
version = "0.1.0"
authors = ["Pucher, Jonas <Jonas.Pucher@v2c2.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
